imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: service_aliases.yml }
  - { resource: @AppBundle/Resources/config/form.yml }
  - { resource: @AppBundle/Resources/config/service.yml }
  - { resource: @AppBundle/Resources/config/listener.yml }

framework:
  translator:
    fallback: "%locale%"
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation:
    enable_annotations: true
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  trusted_hosts: ~
  trusted_proxies: ~
  session:
      # handler_id set to null will use default session handler from php.ini
      handler_id:  ~
      cookie_httponly: true
  fragments: ~
  http_method_override: true
  assets:
    version: %asset_version%

twig:
  debug: "%kernel.debug%"
  strict_variables: true
  form_themes:
    - "AppBundle::forms.html.twig" # default bootstrap3 horizontal form theme
  globals:
    google_api_key: %google_places_key%
    lp_api_key: %lp_express_key%

doctrine:
  dbal:
    driver:   "%database_driver%"
    host:     "%database_host%"
    port:     "%database_port%"
    dbname:   "%database_name%"
    user:     "%database_user%"
    password: "%database_password%"
    charset:  UTF8

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true

doctrine_migrations:
  dir_name: %kernel.root_dir%/../src/AppBundle/Migration
  namespace: AppBundle\Migration
  table_name: app_migrations
  name: App migrations

swiftmailer:
  transport: "%mailer_transport%"
  host:      "%mailer_host%"
  username:  "%mailer_user%"
  password:  "%mailer_password%"
  auth_mode: "%mailer_auth_mode%"
  port:      "%mailer_port%"
  spool:     { type: memory }

ewz_recaptcha:
  public_key:  %recaptcha_public_key%
  private_key: %recaptcha_private_key%
  locale_key:  %kernel.default_locale%

knp_menu:
  twig:
    template: "::menu.html.twig"

vich_uploader:
  db_driver: orm
  storage:   file_system

  mappings:
    attachment:
      uri_prefix:         /uploads
      upload_destination: %kernel.root_dir%/../httpdocs/uploads
      namer:              vich_uploader.namer_uniqid
      delete_on_update:   false
      delete_on_remove:   false
    image:
      uri_prefix:         /images/
      upload_destination: %kernel.root_dir%/../httpdocs/images/
      namer:              vich_uploader.namer_uniqid
    documents:
      uri_prefix:         /documents/
      upload_destination: %kernel.root_dir%/../httpdocs/documents/
      namer:              vich_uploader.namer_uniqid

liip_imagine:
  resolvers:
    default:
      web_path:
        web_root: %kernel.root_dir%/../httpdocs
#        cache_prefix: uploads/cache

  loaders:
    default:
      filesystem:
        data_root: %kernel.root_dir%/../httpdocs

  filter_sets:
    cache: ~
    profile_large:
      quality: 85
      filters:
        upscale: { min: [400, 400] }
        thumbnail: { size: [400, 400], mode: outbound }
    profile_small:
      quality: 85
      filters:
        upscale: { min: [150, 150] }
        thumbnail: { size: [150, 150], mode: outbound }

stfalcon_tinymce:
  include_jquery: true
  tinymce_jquery: true
  language: "%locale%"
  theme:
      simple:
          paste_data_images: true
          plugins:
              - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
              - "searchreplace wordcount visualblocks visualchars code fullscreen"
              - "insertdatetime media nonbreaking save table contextmenu directionality"
              - "emoticons template paste textcolor"
          toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
          toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
          image_advtab: true
          templates:
              - {title: 'Test template 1', content: 'Test 1'}
              - {title: 'Test template 2', content: 'Test 2'}
